### ISSUE TITLE
stars 0.3-0 errors on CRAN/solaris

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#120]
see here: https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/stars-00check.html
@mdsumner @dblodgett-usgs error happening in ncmeta it seems.

**Comment by mdsumner** [comment]
I doubt there's any sensible fix trying to support solaris here. it would be enormously difficult to get the software updated for these files.  We could conditionally prevent the examples and tests on that OS ? Is that how one goes about this?   

I'm pretty sure this is the attempts to open `test_stageiv_xyt.nc` and `inst/nc/bcsd_obs_1999.nc`, so I'll just turn them off pending other ideas. 

I've ignored solaris in the past, several of my packages error because of GDAL or NetCDF requirements and I don't consider it important. The general vibe I see seems to be to dumb down or remove examples and tests - is that what we have to do?  That seems fine for tests given that we can `skip_on("OS")` but it obviously makes some of the examples pretty ugly, so maybe better to remove those.

**Comment by edzer** [comment]
It's usually an indication of _something_, given that numerous other tests involving netcdf files pass. Solaris was useful when I wrote `sf`, since it was the only big-endian machine around, but I believe that was the spark branch that went out of business. 

Having said that, it's hard to debug and I'm fully OK with a not-on-solaris condition on these tests.

**Comment by mdsumner** [comment]
@dblodgett-usgs do you know how to find out the *version-status* of a NetCDF file? I see "ChunkSize" in the `gdalinfo test_stageiv_xyt.nc` which makes it clearly NetCDF-4, but I can't see anything similar for  `bcsd_obs_1999.nc`. Is there a CLI tool that provides that info? (Groups, chunking, and compound types are the version-4 features, but I can't see that this file has those).

**Comment by adrfantini** [comment]
> @dblodgett-usgs do you know how to find out the _version-status_ of a NetCDF file? I see "ChunkSize" in the `gdalinfo test_stageiv_xyt.nc` which makes it clearly NetCDF-4, but I can't see anything similar for `bcsd_obs_1999.nc`. Is there a CLI tool that provides that info? (Groups, chunking, and compound types are the version-4 features, but I can't see that this file has those).

`ndcump -k`?

**Comment by mdsumner** [comment]
LOL, well that was gratifying!  They are both NetCDF-4. Thanks :0

**Comment by dblodgett-usgs** [comment]
Does the Solaris RNetCDF not support reading NetCDF4? Those files could be converted to NetCDF3 of needed. `nccopy -k nc3 in.nc out.nc`

**Comment by mdsumner** [comment]
ooh that might do it, good idea

**Comment by edzer** [comment]
Thanks! Now gone with 0.3-1.
