### ISSUE TITLE
How to perform combinations (difference, multiplication) between non-conformable arrays?

### ISSUE THREAD

**Issue by adrfantini** [r-spatial/stars#187]
Let's say I want to subtract the values of a specific layer (`x[,,,1]`) from all layers (`x`). I can do it this way:
```R
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
(split(x, 'band') - x[,,,1] %>% adrop) %>% merge
# then fix the merged dimension...
```
This approach does not work as well with datasets which have multiple variables.

Obviously a much more intuitive way would be to just do `x - x[,,,1]`, which currently results in this error:
```
Error in .Primitive("-")(dots[[1L]][[1L]], dots[[2L]][[1L]]) : 
  non-conformable arrays
```
The package `raster` works with this kind of approach (e.g. `rasterStacks` can be combined with `rasterLayers`) and this is extremely handy. Can this be implemented for `stars`?

**Comment by edzer** [comment]
Thanks! Now stuff like
```r
x - x[,,,1]
```
should work.

**Comment by adrfantini** [comment]
Awesome!

**Comment by nick-gauthier** [comment]
Note that while this generally works for combining 3d and 2d arrays (such as subtracting the mean band value) it fails in the edge case where the "x" and "band" dimensions have the same number of values.
```
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
xbar = st_apply(x, 1:2, mean)

x - xbar # works with warning about mismatched dimension lengths
x[,1:5] - xbar[,1:5] # same as above
x[,1:6] - xbar[,1:6] # fails because both x and bands have length 6
```

This happens because `Ops.stars` uses `if (!all(dim(e1) == dim(e2)))`, which recycles elements of the shorter vector. So `all(dim(x[,1:5]) == dim(xbar[,1:5])) == FALSE` but `all(dim(x[,1:6]) == dim(xbar[,1:6])) == TRUE`, which sends the latter case to `mapply` instead of `lapply` resulting in the same error as above.

**Comment by edzer** [comment]
Thanks - this should fix it.
