### ISSUE TITLE
TRMM netCDF file is fliped / rotated 

### ISSUE THREAD

**Issue by dvictori** [r-spatial/stars#199]
I downloaded a daily trmm netCDF file from [Nasa DISC](https://disc.gsfc.nasa.gov/SSW/#keywords=TRMM_3B42_daily%207). These files have an issue that when opening with GDAL they come flipped / rotated. 

When using the `raster` package I would use a mix of *flip* and *rotate* to fix the data. But I have no idea how to achieve this using `stars`.

Some test code. You can download the netCDF file from here:
https://drive.google.com/open?id=1xaDZqQ9NaywRwPHy6bDurufXC430C7IE

```
library(tidyverse)
library(sf)
library(stars)

trmm_gdal <- read_stars("3B42_Daily.19991231.7.nc4.nc4")

# I get this warning
# Warning message:
#   In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
#                      GDAL Message 1: No UNIDATA NC_GLOBAL:Conventions attribute

# Plot does not like the file name
plot(trmm_gdal, col = viridis::viridis(10),
     breaks = seq(0, 150, 15))

# Error in parse(text = str) : <text>:1:2: unexpected symbol
# 1: 3B42_Daily.19991231.7.nc4.nc4
# 
# Renaming fixes the plot
trmm_gdal <- trmm_gdal %>% setNames("precipitation")

# But it is rotated
plot(trmm_gdal, col = viridis::viridis(10),
     breaks = seq(0, 150, 15))
```
![image](https://user-images.githubusercontent.com/5786553/62368724-d388d480-b503-11e9-95af-1b93bb1bd520.png)

Opening the same file in Panoply gives:
![image](https://user-images.githubusercontent.com/5786553/62368844-282c4f80-b504-11e9-9e77-23d2d8105fcf.png)

Looking at the dimensions, we see that something is wrong:
```
st_dimensions(trmm_gdal)
  from  to offset delta refsys point values    
x    1 268    -50  0.25     NA    NA   NULL [x]
y    1 209  -32.5 -0.25     NA    NA   NULL [y]
```
In Panoply we get
![image](https://user-images.githubusercontent.com/5786553/62368974-848f6f00-b504-11e9-99a5-a768cab477b6.png)

So, any idea what is going on and how to flip / rotate this image? I also tried reading using `read_ncdf` but results are the same.

Thanks

**Comment by adrfantini** [comment]
The file is not CF-Compliant. This unfortunately is quite common with satellite data. The issue lies in the fact that coordinate dimensions in the variable of interest (precipitation) are not in the prescribed order (T,Z,Y,X), and are instead (lon, lat). This can be easily fixed with a single command from the NCO suite:
```
ncpdq -a lat,lon 3B42_Daily.19991231.7.nc4.nc4 flipped.nc
```

I guess that to flip the data inside `stars` you would have to swap the assignment of the `x` and `y` axis.

**Comment by dblodgett-usgs** [comment]
@adrfantini -- to be more precise, the file isn't COORDS compliant and doesn't claim to use CF conventions at all. COORDS is where the canonical axis order came from and CF relaxes that requirement. 

The problem here, IMHO, is that no conventions are declared at all so we basically have to assume COORDS. However, using the units, we can infer the actual axis of the coordinate variables. I wrote this hot mess: https://github.com/hypertidy/ncmeta/blob/master/R/nc_coord.R#L166 over in `ncmeta` to take care of that kind of thing but it hasn't made it into `read_ncdf`.

**Comment by adrfantini** [comment]
Oh, yep, you are correct. In any case AFAIK most programs assume the ordering is the one mandated by COARDS, so `stars` is not alone in this.

**Comment by dblodgett-usgs** [comment]
Alas... it's true. It _is_ possible to use CF attributes to figure it out though. I've got that implemented for 1d and 2d coordinate variables over here: https://github.com/USGS-R/intersectr/blob/master/R/execute_intersection.R#L248

**Comment by dvictori** [comment]
Thanks for the NCO tip. Will use that prior to importing the data. For now what I was doing was opening the data using `raster`, flip and transpose as needed, and then convert to `stars`. I just though that `stars` would be able to transpose and flip the data also.

**Comment by edzer** [comment]
To some extent:
```r
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x1 = read_stars(tif)
x1[[1]] = x1[[1]][,352:1,] # flip: reverse y coordinate
plot(x1)
```

![x](https://user-images.githubusercontent.com/520851/62733531-1c221f80-ba27-11e9-885c-604c1c8b9767.png)


this works since stars objects are (lists of) R arrays. But you can only use this trick when dimension order doesn't change, for more manipulations you'd have to update the dimensions table.

```r
x1[[1]][349:1,352:1,]
```
reverses both x and y.
