### ISSUE TITLE
issue with "new_dim" temporary name

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/stars#22]
I don't totally get the context yet, so this is a bit of a blind report - but it's a useful data set for experimenting with high-D. 

This file has an interesting set of two 4D and two 5D variables (subdatasets), they are individually on four different grids. 

```
https://github.com/potterzot/easyncdf/raw/master/tests/data/test.nc4
```

Obtain that file, or install the package, get the sds names: 

```R
f <- system.file("tests/data/test.nc4", package = "easyncdf")
sds <- c("Precipitable_water_entire_atmosphere_single_layer_ens", "Total_precipitation_surface_6_Hour_Accumulation_ens", 
"v-component_of_wind_isobaric_ens", "Minimum_temperature_height_above_ground_6_Hour_Minimum_ens")
## ncmeta::nc_vars(f) %>% dplyr::filter(ndims > 3) %>% dplyr::pull(name)
```

Each variable ends up with "new_dim", as an extra dim - which doesn't belong: 

```R
lapply(sds, function(x) names(st_dimensions(stars::read_stars(f, sub = x))))
```

*I believe* that means this line must be a loop so that `dim_name` is passed explicitly via `c`, but there's probably a better solution (and I couldn't get it to work). 

https://github.com/r-spatial/stars/blob/d05fe4b8e5732ab7ddf808d5879113362e4990e3/R/stars.R#L56

**Comment by adrfantini** [comment]
I also found that sometimes this "new_dim" pops up.

**Comment by edzer** [comment]
This should be gone now. 

What I had done was modify `c.stars` such that `c(obj)` (i.e., calling it with a single stars object) collapses attributes into a dimension. Being able to do that (and the reverse) is very useful, but how do we call these operations?

Right now, `split.stars` and `merge.stars` do the same, split a single attribute along a dimension, or merge several attributes into a dimension. I propose to drop this behavior from `c.stars` since in R, `c(obj)` typicall does nothing (except optionally strip names).

**Comment by edzer** [comment]
Thanks for checking btw; I tried the same when @potterzot 's easyncdf passed by on twitter, and obviously assumed the `new_dim` issue was in the data, not mine!

**Comment by potterzot** [comment]
Hope it was useful! For reference that data is from the UCAR THREDDS server for the [GEFS data](http://thredds.ucar.edu/thredds/catalog/grib/NCEP/GEFS/Global_1p0deg_Ensemble/members/catalog.html). I've worked with it a few times and it seems like a nice example since variables have different sets of dimensions.
