### ISSUE TITLE
st_apply stopped working for FUN=var

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/stars#430]
The code below works for stars 0.4-3, but fails for the current version:

``` r
library(stars)
tif = system.file("tif/L7_ETMs.tif", package = "stars")
x = read_stars(tif)
st_apply(x, 1:2, var) # var band value for each pixel
#> stars object with 2 dimensions and 1 attribute
#> attribute(s):
#>       var        
#>  Min.   :   0.0  
#>  1st Qu.: 227.4  
#>  Median : 346.3  
#>  Mean   : 537.3  
#>  3rd Qu.: 594.2  
#>  Max.   :7788.8  
#> dimension(s):
#>   from  to  offset delta                       refsys point values x/y
#> x    1 349  288776  28.5 UTM Zone 25, Southern Hem... FALSE   NULL [x]
#> y    1 352 9120761 -28.5 UTM Zone 25, Southern Hem... FALSE   NULL [y]
```

**Comment by edzer** [comment]
This has better heuristics for choosing between unary or n-ary version of FUN; note that e.g. `terra` uses two "verbs" for this: `lapp` for the multi, `app` for the unary (afaict). This is not water tight, but catches the case above. Note also that `var` when used in
```r
st_apply(x, 3, var)
```
does not what you'd expect, because `var` applied to a matrix (=raster layer) computes the covariance matrix of the colums, not the variance of the entire matrix. `sd` does this, and for variance one would need to use
```r
st_apply(x, 3, function(x) var(as.vector(x)))
```
I think this needs to be added to the docs.

**Comment by Nowosad** [comment]
Thank you!
