### ISSUE TITLE
NetCDF driver missing from GDAL in OSX binary packages

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#566]
See https://cran.r-project.org/web/checks/check_results_stars.html : package `stars` now errors on reading NetCDF files on all OSX platforms. It reads raster data through GDAL, which is provided by `sf`. I just checked on an OSX machine, and the `NetCDF` driver in GDAL is missing (e.g. in both `sf` and `terra`). This used to not be the case. Other R packages (`ncdf4`, `RNetCDF`) work fine, so NetCDF seems to work on OSX. I looked into the recipes file for GDAL [here](https://github.com/R-macos/recipes/blob/master/recipes/gdal) and wondered whether `netcdf` should be listed in `Depends:` ?

@s-u could you pls take a look at this, when you get some time?
Cc: @rhijmans @rsbivand

**Comment by s-u** [comment]
@edzer yes, you're right, `gdal` is missing `netcdf` in `Depends:`. It happened to work when the binaries were built over existing runs where netcdf was already installed, but now that things are built automatically on a clean VM the dependencies matter. I'll try to rebuild and install new binaries this week.

**Comment by s-u** [comment]
BTW: please file this in https://github.com/R-macos/recipes so it can be addressed.

**Comment by rsbivand** [comment]
The **sf** patch for  the development version of Rtools42 is at https://www.r-project.org/nosvn/winutf8/ucrt3/patches/CRAN/sf.diff, for **terra** same directory. These libraries have extended recently to cover 

- Szip compression of HDF5 files (-lsz is already in the macOS GDAL recipe, but I think from szip given the Depends line in https://github.com/R-macos/recipes/blob/master/recipes/gdal rather than libaec, see https://github.com/rspatial/terra/issues/686; HDF5 build) https://github.com/R-macos/recipes/blob/master/recipes/hdf5 should use aec https://svn.r-project.org/R-dev-web/trunk/WindowsBuilds/winutf8/ucrt3/toolchain_libs/mxe/src/hdf5.mk, 
- BLOSC compression of ZARR files, 
- Geospatial PDF, 
- KEA, 
and others that users had motivated.

**Comment by edzer** [comment]
I added a PR to R-macos/recipes: https://github.com/R-macos/recipes/pull/33

**Comment by s-u** [comment]
@edzer, @rsbivand can you, please, check latest binaries for arm64? (use https://mac.R-project.org as CRAN mirror) The latest recipes should have the drivers that were requested. If there is anything else you need, please supply details with libraries are needed.

**Comment by s-u** [comment]
I think that is an old sync, I don't see any issue on my end:

```
> available.packages(rep="https://mac.R-project.org")["sf",1:2]
Package Version 
   "sf" "1.0-9" 
```

```
$ tail big-sur-arm64/results/4.2/sf.Rcheck/00check.log 
  ‘sf5.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘sf6.Rmd’ using ‘UTF-8’... [0s/0s] OK
  ‘sf7.Rmd’ using ‘UTF-8’... [0s/0s] OK
* checking re-building of vignette outputs ... [15s/18s] OK
* checking PDF version of manual ... OK
* DONE
Status: 1 NOTE
* using check arguments '--no-clean-on-error '

* elapsed time (check, wall clock): 4:02
```

**Comment by edzer** [comment]
Libraries for `arm` work, as seen [here](https://cran.r-project.org/web/checks/check_results_stars.html), for `x86_64` both platforms still fail.

**Comment by s-u** [comment]
@edzer Thanks for the confirmation. I have not updated the x86 build machines yet - will do now.

**Comment by edzer** [comment]
Looks like this now works for both [r-release-macos](https://cran.r-project.org/web/checks/check_results_stars.html) flavors - thanks!

**Comment by s-u** [comment]
Thanks, @edzer, now that both arm64 and x86_64 are both on Big Sur I hope the issues will diminish. Also please let me know if/when you want me to update GDAL - I was holding back since there are often issues with the latest releases and package compatibility so I won't try to update to any non-patch version unless I get ok from you.

**Comment by rsbivand** [comment]
@s-u We have https://github.com/r-spatial/sf/issues/2156 needing to write OpenFileGDB out, this was added to GDAL in 3.6. If you are ready (with cmake), GDAL is at 3.6.4 now (you are right, 3.6.0 was withdrawn and 3.6.1 didn't last long), and 3.7 is expected soon.
